/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bab5;

/**
 *
 * @author RPL-SMKN 4 BOGOR
 */
public class bagian1 extends javax.swing.JFrame {

    /**
     * Creates new form bagian1
     */
    public bagian1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CChickenKatsu = new javax.swing.JCheckBox();
        CNasiGoreng = new javax.swing.JCheckBox();
        CUdangManis = new javax.swing.JCheckBox();
        aSusu = new javax.swing.JCheckBox();
        aMatcha = new javax.swing.JCheckBox();
        aCoffee = new javax.swing.JCheckBox();
        jNAMA = new javax.swing.JLabel();
        jALAMAT = new javax.swing.JLabel();
        jMAKANAN = new javax.swing.JLabel();
        jMINUMAN = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        bPESAN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CChickenKatsu.setText("Chicken Katsu");

        CNasiGoreng.setText("Nasi Goreng");

        CUdangManis.setText("Udang Manis");

        aSusu.setText("Susu");

        aMatcha.setText("Matcha");

        aCoffee.setText("Coffee");

        jNAMA.setText("NAMA");

        jALAMAT.setText("ALAMAT");

        jMAKANAN.setText("MAKANAN");

        jMINUMAN.setText("MINUMAN");

        bPESAN.setText("PESAN");
        bPESAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPESANActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMAKANAN)
                            .addComponent(jNAMA)
                            .addComponent(jALAMAT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CNasiGoreng)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CChickenKatsu)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(jTextField2))
                            .addComponent(CUdangManis))
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMINUMAN)
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aMatcha)
                            .addComponent(aSusu)
                            .addComponent(aCoffee))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPESAN)
                .addGap(109, 109, 109)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNAMA)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jALAMAT))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CChickenKatsu)
                    .addComponent(jMAKANAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CNasiGoreng)
                .addGap(6, 6, 6)
                .addComponent(CUdangManis)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSusu)
                    .addComponent(jMINUMAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMatcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aCoffee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPESAN)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPESANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPESANActionPerformed
         StringBuilder summary = new StringBuilder();

             summary.append("Nama: ").append(jTextField1.getText()).append("\n");
             summary.append("Alamat: ").append(jTextField2.getText()).append("\n");
            summary.append("Makanan: \n");

            if (CChickenKatsu.isSelected()) summary.append(" - Chicken Katsu\n");
            if (CNasiGoreng.isSelected()) summary.append(" - Nasi Goreng Goreng\n");
            if (CUdangManis.isSelected()) summary.append(" - Udang Manis\n");

            summary.append("Minuman: \n");

            if (aSusu.isSelected()) summary.append(" - Susu\n");
            if (aMatcha.isSelected()) summary.append(" - Matcha\n");
            if (aCoffee.isSelected()) summary.append(" - Coffee\n");
            
        // Display the summary in the JTextArea
        jTextArea1.setText(summary.toString());
            
        
    }//GEN-LAST:event_bPESANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bagian1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bagian1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bagian1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bagian1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bagian1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CChickenKatsu;
    private javax.swing.JCheckBox CNasiGoreng;
    private javax.swing.JCheckBox CUdangManis;
    private javax.swing.JCheckBox aCoffee;
    private javax.swing.JCheckBox aMatcha;
    private javax.swing.JCheckBox aSusu;
    private javax.swing.JButton bPESAN;
    private javax.swing.JLabel jALAMAT;
    private javax.swing.JLabel jMAKANAN;
    private javax.swing.JLabel jMINUMAN;
    private javax.swing.JLabel jNAMA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
