/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.modul6;

/**
 *
 * @author PC RPL - R1
 */
public class bagian2 extends javax.swing.JFrame {

    /**
     * Creates new form bagian2
     */
    public bagian2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMAKANAN = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMINUMAN = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jOLAHRAGA = new javax.swing.JList<>();
        jresume = new javax.swing.JLabel();
        cPROSES = new javax.swing.JButton();
        cBersih = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMAKANAN.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ayam Goreng", "Rendang", "Telur Balado", "Sushi", "Ikan Bakar" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jMAKANAN);

        jMINUMAN.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Susu", "Es Buah", "Es Cendol", "Coffee", "Cincau" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jMINUMAN);

        jOLAHRAGA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Taekwondo", "Renang", "Volly Ball", "Basket", "Bulu Tangkis" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jOLAHRAGA);

        jresume.setText("Resume");

        cPROSES.setText("Proses");
        cPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPROSESActionPerformed(evt);
            }
        });

        cBersih.setText("Bersih");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cBersih)
                            .addComponent(cPROSES))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jresume)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jresume)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(cPROSES)
                                .addGap(18, 18, 18)
                                .addComponent(cBersih))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPROSESActionPerformed
        // Mendapatkan indeks terpilih dari ListMakan
int IndexMakanan = jMAKANAN.getSelectedIndex();

// Mendapatkan indeks terpilih dari ListMinuman
int IndexMinMinuman = jMINUMAN.getMinSelectionIndex();
int IndexMaxMinuman = jMINUMAN.getMaxSelectionIndex();

// Mendapatkan indeks terpilih dari ListOlahraga
int[] selectedIndicesOlahraga = jOLAHRAGA.getSelectedIndices();

// Membuat string untuk menampilkan hasil
String Kalimat;
Kalimat = "Daftar Makanan yang dipilih : \n";
Kalimat = Kalimat + jMAKANAN.getModel().getElementAt(IndexMakanan).toString() + "\n";
Kalimat = Kalimat + "Daftar Minuman yang dipilih : \n";

// Menambahkan daftar minuman yang dipilih
for (int i = IndexMinMinuman; i <= IndexMaxMinuman; i++) {
    Kalimat = Kalimat + jMINUMAN.getModel().getElementAt(i).toString() + "\n";
}

// Menambahkan daftar olahraga yang dipilih
Kalimat = Kalimat + "Daftar Olahraga yang dipilih : \n";
for (int i : selectedIndicesOlahraga) {
    Kalimat = Kalimat + jOLAHRAGA.getModel().getElementAt(i).toString() + "\n";
}

// Menampilkan hasil ke MemoResume
jTextArea2.setText(Kalimat);
    }//GEN-LAST:event_cPROSESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bagian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bagian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bagian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bagian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bagian2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBersih;
    private javax.swing.JButton cPROSES;
    private javax.swing.JList<String> jMAKANAN;
    private javax.swing.JList<String> jMINUMAN;
    private javax.swing.JList<String> jOLAHRAGA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jresume;
    // End of variables declaration//GEN-END:variables
}
